# The URL the site will be built for
base_url = "https://ianmkenney.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "DeepThought"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
katex.enabled = true
katex.auto_render = true

navbar_items = [
    { code = "en", nav_items = [
        { url = "$BASE_URL/", name = "Home" },
        # { url = "$BASE_URL/projects", name = "Projects" },
        { url = "$BASE_URL/posts", name = "Posts" },
        { url = "$BASE_URL/jokes", name = "Quality Jokes" },
    ] },
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "Ian Kenney"
avatar = "https://avatars.githubusercontent.com/u/7085164?s=400&u=24f18f55eabb4d6627badfda3bd76ef5a01940db&v=4"

[extra.social]
github = "ianmkenney"
linkedin = "ianmkenney"
discord = "rulemaster"
orcid = "0000-0002-9749-8866"
google_scholar = "SKI0vH4AAAAJ"