name: Build and deploy GH pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0

      - name: build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        if: github.ref == 'refs/heads/main'
        env:
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}

      - name: build only
        uses: shalzz/zola-deploy-action@v0.17.2
        if: github.event_name == 'pull_request'
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
